server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://100.104.142.32:3306/prac
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  pattern:
    console: >
      {"time":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}",
      "level":"%p",
      "service":"${spring.application.name}",
      "thread":"%t",
      "logger":"%c",
      "msg":"%m",
      "trace":"%X{traceId:-}",
      "span":"%X{spanId:-}"}%n
