spring:
  config:
    import:
      - optional:configserver:http://config-server:8888/consul-client
      - optional:configserver:http://config-server:8888/logging
      - optional:configserver:http://config-server:8888/service-actuator
      - optional:configserver:http://config-server:8888/mysql
server:
  port: 8083
spring:
  application:
    name: comment-service