server:
  port: 8084
spring:
  config:
    import:
      -optional:configserver:http://config-server:8888/consul-client.yaml
      -optional:configserver:http://config-server:8888/service-actuator.yaml
      -optional:configserver:http://config-server:8888/logging.yaml