spring:
  config:
    import:
      -optional:configserver:http://config-server:8888/consul-client
      -optional:configserver:http://config-server:8888/gateway-actuator
      -optional:configserver:http://config-server:8888/logging

  application:
    name: gateway

  autoconfigure:
      exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      server:
          webflux:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true

server:
  port: 8080