server:
  port: 8080

spring:
  config:
    import:
      - configserver:http://config-server:8888/consul-client.yaml
      - configserver:http://config-server:8888/gateway-actuator.yaml
      - configserver:http://config-server:8888/logging.yaml

  application:
    name: gateway

  autoconfigure:
      exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      server:
          webflux:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
