spring:
  config:
    import:
      -optional:configserver:http://config-server:8888/consul-client.yml
      -optional:configserver:http://config-server:8888/gateway-actuator.yml
      -optional:configserver:http://config-server:8888/logging.yml

server:
  port: 8080

spring:
  application:
    name: gateway

  autoconfigure:
      exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      server:
          webflux:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
