spring:
    cloud:
        consul:
            host: consul
            port: 8500
            discovery:
                prefer-ip-address: true
                health-check-path: /actuator/health
                health-check-interval: 10s